### PR TITLE
Fix low speed braking and handbrake

### PR DESCRIPTION
**Pull request by Dechode**

### CODE REVIEW

**Comment by michurebmann** [comment]
i tested it and it looks fine so far, its hart to tell on these textures, you can hardly guess if its still moving a bit, or not but its clearly better

from gameplay perspective, the handbrake calculation is maybe fine, bacause most people will probably have a button for handbrake and cannot bull the handbrake just a bit.
but in real life, the handbrake add up on the normal brake instead of doing:  max(brake, handbrake).
but i think is ok like that.

**Comment by Dechode** [comment]
> but in real life, the handbrake add up on the normal brake instead of doing: max(brake, handbrake).

I think you are correct. I will change it to add the torques.

**Comment by michurebmann** [comment]
i dont think it will matter much, its just a minor detail!
one will just recognize if the handbrake is on a axis rather then a button....

**Comment by Dechode** [comment]
This is true, but it was a simple fix so might as well do it while I'm at it. I will merge this now

**Pull request merged**
